authors:
  kjuulh:
    name: "kjuulh"        # Author name
    description: "No/Nothing" # Author description
    avatar: https://git.front.kjuulh.io/avatars/260eef75e2c53962646a315683a1d1e5?size=512
    # slug: url           # Author profile slug
    # url: url            # Author website URL
